### ISSUE TITLE
North America subregions no longer in list

### ISSUE THREAD

**Issue by nnhubbard** [julien-noblet/download-geofabrik#217]
North America sub regions such as `us-west` are no longer in the list, but they ARE available for download on geofabrik. Do you know what the issue might be?

**Comment by julien-noblet** [comment]
You're right!
Sub regions are in a table named(by ID) "subregions".

There is also some case there are some others in a "specialsubregions" table. Please have a look at #218

**Comment by julien-noblet** [comment]
You can try binaries from https://github.com/julien-noblet/download-geofabrik/releases/tag/v2.5.1-rc0
They should be available soon.
