### ISSUE TITLE
Failed to download georgia-eu

### ISSUE THREAD

**Issue by fatelgit** [julien-noblet/download-geofabrik#222]
First of all: I love the package, works like a charm for a while now! :)
Recently I was trying to download the pbf-File for "georgia" (europe) and noticed the following bug:

cd ~/Downloads/download-geofabrik_2.5.1-rc0_Linux_x86_64$ 

`./download-geofabrik download georgia-eu`
   ⨯ can't download element    error=error while downloading https://download.geofabrik.de/europe/georgia-eu-latest.osm.pbf, server return code 404
Please use './download-geofabrik generate' to re-create your yml file

`./download-geofabrik generate`
[...]
   • geofabrik.yml generated.

`./download-geofabrik download georgia-eu`
   ⨯ can't download element    error=error while downloading https://download.geofabrik.de/europe/georgia-eu-latest.osm.pbf, server return code 404
Please use './download-geofabrik generate' to re-create your yml file

When renaming "georgia-eu" to "georgia" in geofabrik.yml manually it works again but since we are using the script to download single countries from the complete planet it would stop working for "georgia-us" again.

**Comment by julien-noblet** [comment]
Wow! I've missed something while redesign my scrapper/generator.
In fact, it have to add a line fore these 2 elements:
```
file: georgia
```
I'm working on a patch

**Comment by julien-noblet** [comment]
@fatelgit Please have a look at [v2.5.1-rc1](https://github.com/julien-noblet/download-geofabrik/releases/tag/v2.5.1-rc1) it should fix this issue :smile:

**Comment by fatelgit** [comment]
Works now as expected - thank you for helping out that fast!
