### ISSUE TITLE
Show program version

### ISSUE THREAD

**Issue by ImreSamu** [julien-noblet/download-geofabrik#27]
For debugging and testing it will be useful to query the version number.

As I know it is not possible yet.

**Comment by julien-noblet** [comment]
Look at [v2.2.0-beta-fix#27](https://github.com/julien-noblet/download-geofabrik/releases/tag/v2.2.0-beta-fix%2327).

**Comment by ImreSamu** [comment]
Thank you !

```
root@31ebeabf9f08:/tools# ./download-geofabrik --version
2.2.0-beta
root@31ebeabf9f08:/tools#
```

**Comment by julien-noblet** [comment]
OK so I'm closing this issue
