### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by julien-noblet** [julien-noblet/download-geofabrik#29]
@ImreSamu, I'm looking into your project, :smile: 
as I see, you are using docker to launch your apps.

Do you think it could be usefull to have a docker image of download-geofabrik?

I'm thinking about something like this:
``` docker run download-geofabrik download xxx --all-your-flags --data=/data```

I've seen some :octocat:github hooks to push all releases to :whale: hub.docker.org so there is a zero maintenance and it will auto downloading the lastest version of download-geofabrik.

**Comment by ImreSamu** [comment]
>Do you think it could be useful to have a docker image of download-geofabrik?

honestly,   I don't know.

imho:
* for a simple command line user:  the ` download-geofabrik` binary release is perfect, and most of the time is optimal. 
   * ( except, that no automatic "binary" refreshing )
* for integrating with other tools: my best practice is changing, all the time.  

so I don't have a "clear answer"

**Comment by julien-noblet** [comment]
I will distribute Docker images since v2.5.
I'm not sure it will be used but I'll look at Docker metrics.
