### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by uxoof** [julien-noblet/download-geofabrik#8]
is it possible to run download-geofabrik behind corporate proxy. because we meet error like below:

Error while downloading  https://raw.githubusercontent.com/julien-noblet/download-geofabrik/stable/geofabrik.yml - Get https://raw.githubusercontent.com/julien-noblet/download-geofabrik/stable/geofabrik.yml: dial tcp 151.101.8.133:443: getsockopt: connection refused

guide me please. thanks ..

**Comment by julien-noblet** [comment]
Can you try this PR #14 ?

**Comment by julien-noblet** [comment]
Add --proxy-user && --proxy-pass with http proxy.
It will be better than --proxy-http=user:pass@proxy:8080

**Comment by julien-noblet** [comment]
Fixed by #14
